cliente = str(input("Digite o nome do cliente: "))
diaVencimento = int(input("Digite o dia de vencimento: "))
mesVencimento = str(input("Digite o mês de vencimento: "))
fatura = str(input("Digite o valor da fatura: "))
print("Olá,",cliente)
print("A sua fatura com vencimento em",diaVencimento,"de",mesVencimento,"no valor de R$",fatura,"está fechada.")